In [111]:
import numpy as np

Creación e Indexación:

In [112]:
# Ejercicio 1: Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

a1 = np.random.randint(10, 99, (50,))
print(a1)

print("-----")

multi = a1[::5]
print(multi)


[56 64 22 28 57 35 97 88 72 27 70 70 81 63 66 68 19 25 50 15 11 55 19 70
 81 80 22 61 82 55 26 76 50 94 21 35 97 52 87 86 92 56 44 22 60 83 73 32
 27 48]
-----
[56 35 70 68 11 80 26 35 92 83]


In [113]:
# Ejercicio 2: Crea un array 1D con 30 valores aleatorios del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.


a1_2 = np.random.randint(1, 21, (30,))
print(a1_2)

print("-----")

imp = a1_2[1::2]
print(imp)


[16  4 15  3  7 14 10 14 13 18  5 15  6 12  6 14 12  4 16  1 12  6 11 10
 12 19 19 11 16 10]
-----
[ 4  3 14 14 18 15 12 14  4  1  6 10 19 11 10]


In [114]:
# Ejercicio 3: Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

d2 = np.random.uniform(1, 5, (4, 6))  # numpy.random.randint(low, high, size, dtype)
print(d2)

print("-----")

print(d2[-1])

print("-----")

redondeo = np.round(d2, 2) 
print(redondeo)

[[2.78514674 3.20115182 1.52392085 2.0559511  3.61991104 3.79974902]
 [1.34064554 2.29980056 1.1175075  1.95767945 4.15403006 1.67251451]
 [4.92048866 1.00346519 3.08128293 4.82142511 1.89227762 1.0261356 ]
 [1.00953598 2.51673354 4.10587667 2.88158026 2.59052468 4.92766646]]
-----
[1.00953598 2.51673354 4.10587667 2.88158026 2.59052468 4.92766646]
-----
[[2.79 3.2  1.52 2.06 3.62 3.8 ]
 [1.34 2.3  1.12 1.96 4.15 1.67]
 [4.92 1.   3.08 4.82 1.89 1.03]
 [1.01 2.52 4.11 2.88 2.59 4.93]]


Funciones Aritméticas y Estadísticas:

In [115]:
# Ejercicio 1: Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

d3 = np.round(np.random.rand(2, 3, 5), 1)
print(d3)

[[[0.8 0.9 0.7 0.1 1. ]
  [0.6 0.6 0.6 0.4 0.5]
  [0.1 0.9 0.7 0.2 0.8]]

 [[0.6 0.9 0.6 0.4 0.1]
  [0.2 0.  0.6 0.6 0.3]
  [0.7 0.7 0.4 0.1 0.5]]]


In [116]:
# Ejercicio 2: Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

d3_2 = np.empty((2, 3, 5), dtype = "U1") # Para crear un espacio vacío nuevo
print(d3_2)

[[['' '' '' '' '']
  ['' '' '' '' '']
  ['' '' '' '' '']]

 [['' '' '' '' '']
  ['' '' '' '' '']
  ['' '' '' '' '']]]


In [117]:
# Si el valor del array es igual que la media, se reemplaza por "A".

media = np.round(np.mean(d3), 1)
print("media:", media)

print("-----")

d3_2[d3 == media] = "A"
print(d3_2)

print("-----")

# Si el valor del array es mayor que la media, se reemplaza por "B".

d3_2[d3 > media] = "B"
print(d3_2)

print("-----")

# Si el valor del array es menor que la media, se reemplaza por "C".

d3_2[d3 < media] = "C"
print(d3_2)

print("-----")

# Si el valor es igual que el máximo, se reemplaza por "D".

max = np.max(d3)
print("máximo:", max)

print("-----")

d3_2[d3 == max] = "D"
print(d3_2)

print("-----")

# Si el valor es igual que el mínimo, se reemplaza por "E".

min = np.min(d3)
print("mínimo:", min)

print("-----")

d3_2[d3 == min] = "E"
print(d3_2)

media: 0.5
-----
[[['' '' '' '' '']
  ['' '' '' '' 'A']
  ['' '' '' '' '']]

 [['' '' '' '' '']
  ['' '' '' '' '']
  ['' '' '' '' 'A']]]
-----
[[['B' 'B' 'B' '' 'B']
  ['B' 'B' 'B' '' 'A']
  ['' 'B' 'B' '' 'B']]

 [['B' 'B' 'B' '' '']
  ['' '' 'B' 'B' '']
  ['B' 'B' '' '' 'A']]]
-----
[[['B' 'B' 'B' 'C' 'B']
  ['B' 'B' 'B' 'C' 'A']
  ['C' 'B' 'B' 'C' 'B']]

 [['B' 'B' 'B' 'C' 'C']
  ['C' 'C' 'B' 'B' 'C']
  ['B' 'B' 'C' 'C' 'A']]]
-----
máximo: 1.0
-----
[[['B' 'B' 'B' 'C' 'D']
  ['B' 'B' 'B' 'C' 'A']
  ['C' 'B' 'B' 'C' 'B']]

 [['B' 'B' 'B' 'C' 'C']
  ['C' 'C' 'B' 'B' 'C']
  ['B' 'B' 'C' 'C' 'A']]]
-----
mínimo: 0.0
-----
[[['B' 'B' 'B' 'C' 'D']
  ['B' 'B' 'B' 'C' 'A']
  ['C' 'B' 'B' 'C' 'B']]

 [['B' 'B' 'B' 'C' 'C']
  ['C' 'E' 'B' 'B' 'C']
  ['B' 'B' 'C' 'C' 'A']]]
